# Generated by Django 5.0 on 2024-03-27 11:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select any category or create one from the snippet', related_name='category_blogs', to='blogs.blogcategory'),
        ),
    ]
