# Generated by Django 5.0 on 2024-03-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='text',
            new_name='comment',
        ),
    ]
