# Generated by Django 5.0 on 2024-03-25 22:45

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_bg_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='why_us',
            field=wagtail.fields.StreamField([('why_us', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('subtitle', wagtail.blocks.CharBlock(label='Subtitle', max_length=400, required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon_class', wagtail.blocks.CharBlock(help_text='ex: flaticon-resume', label='Flat Icon Class Name', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Title', max_length=100, required=False)), ('content', wagtail.blocks.TextBlock(help_text='Content of the card', required=False))], required=False)))]))], blank=True, null=True),
        ),
    ]
