# Generated by Django 5.0 on 2024-03-31 10:44

import streams.models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_why_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='job_categories',
            field=wagtail.fields.StreamField([('job_category', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=400, required=False)), ('sub_heading', wagtail.blocks.CharBlock(label='Sub heading', max_length=500, required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(streams.models.Category)))]))], blank=True, null=True),
        ),
    ]
