# Generated by Django 5.0 on 2024-04-01 11:50

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('about_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('way_to_use', wagtail.fields.StreamField([('way_to_use', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('flat_icon_class', wagtail.blocks.CharBlock(help_text='ex: flaticon-website', label='Flat Icon Class Name', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('content', wagtail.blocks.TextBlock(label='Content', max_length=400, required=False))], required=False)))]))], blank=True, null=True)),
                ('why_us', wagtail.fields.StreamField([('why_us', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('subtitle', wagtail.blocks.CharBlock(label='Subtitle', max_length=400, required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon_class', wagtail.blocks.CharBlock(help_text='ex: flaticon-resume', label='Flat Icon Class Name', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Title', max_length=100, required=False)), ('content', wagtail.blocks.TextBlock(help_text='Content of the card', required=False))], required=False)))]))], blank=True, null=True)),
                ('flex_section', wagtail.fields.StreamField([('flex', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('content', wagtail.blocks.TextBlock(label='Content', max_length=2000, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')], label='Image Position', required=False)), ('link_url', wagtail.blocks.URLBlock(label='external URL', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('btn_label', wagtail.blocks.CharBlock(label='Label', max_length=20, required=False))]))], blank=True, null=True)),
                ('testimonials', wagtail.fields.StreamField([('testimonials', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('subtitle', wagtail.blocks.CharBlock(label='Subtitle', max_length=400, required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('testimonial', wagtail.blocks.TextBlock(label='Testimonial', max_length=2000, required=False)), ('client_name', wagtail.blocks.CharBlock(label='Client Name', max_length=100, required=False)), ('designation', wagtail.blocks.CharBlock(label='Designation', max_length=100, required=False))], required=False)))]))], blank=True, null=True)),
                ('about_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
