# Generated by Django 5.0 on 2024-03-27 11:15

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='way_to_use',
            field=wagtail.fields.StreamField([('way_to_use', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('flat_icon_class', wagtail.blocks.CharBlock(help_text='ex: flaticon-website', label='Flat Icon Class Name', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Title', max_length=200, required=False)), ('content', wagtail.blocks.TextBlock(label='Content', max_length=400, required=False))], required=False)))]))], blank=True, null=True),
        ),
    ]
