# Generated by Django 5.0 on 2024-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('main', 'Main Menu'), ('for_candidate', 'For Candidate'), ('quick_links', 'Quick Links')], default='main', help_text='Select the type of menu', max_length=50),
        ),
    ]
