# Generated by Django 5.0 on 2024-03-27 20:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('english_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('german_content', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impressum page',
                'verbose_name_plural': 'Impressum pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
